stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - npm install
    - npm run test

deploy-job:
    stage: deploy
    script:
        - apt-get update -y
        - apt-get install openssh-client -y
        - apt-get install rsync -y
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        - rsync -avz --delete --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='.gitignore' --exclude='node_modules/' --exclude='package-lock.json' --exclude='package.json' . $SERVER_USER@$SERVER_IP:$SERVER_PATH
        - ssh $SERVER_USER@$SERVER_IP "docker-compose -f $SERVER_PATH/docker-compose.yml up -d"
    only:
        - main






