version: '3.6'

services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    ports:
      - '443:443'
      - '22:22'
      - '80:80'
    volumes:

      - 'GITLAB_config:/etc/gitlab'
      - 'GITLAB_logs:/var/log/gitlab'
      - 'GITLAB_data:/var/opt/gitlab'
      - 'GITLAB_etc:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    shm_size: '256m'


volumes:
    GITLAB_config:
    GITLAB_logs:
    GITLAB_data:
    GITLAB_etc: